"""Top-level shared types — enums, dataclasses, exceptions.

Everything users need to import is re-exported here so callers can write
``from ogpu.types import TaskStatus, OGPUError, Receipt, SourceMetadata``.
"""

from __future__ import annotations

from .enums import (
    DeliveryMethod,
    Environment,
    ResponseStatus,
    Role,
    SourceStatus,
    TaskStatus,
    combine_environments,
    environment_names,
    parse_environments,
)
from .errors import (
    ChainNotSupportedError,
    ConfigError,
    GasError,
    InsufficientBalanceError,
    InsufficientLockupError,
    InvalidRpcUrlError,
    InvalidSignerError,
    IPFSError,
    IPFSFetchError,
    IPFSGatewayError,
    MasterNotFoundError,
    MissingSignerError,
    NonceError,
    NotEligibleError,
    NotFoundError,
    NotMasterError,
    NotProviderError,
    NotSourceOwnerError,
    NotTaskOwnerError,
    OGPUError,
    PermissionError,
    ProviderNotFoundError,
    ResponseAlreadyConfirmedError,
    ResponseNotFoundError,
    SourceInactiveError,
    SourceNotFoundError,
    StateError,
    TaskAlreadyFinalizedError,
    TaskExpiredError,
    TaskNotFoundError,
    TxError,
    TxRevertError,
    UnbondingPeriodNotElapsedError,
    VaultError,
)
from .metadata import (
    ImageEnvironments,
    ResponseParams,
    ResponseSnapshot,
    SourceInfo,
    SourceMetadata,
    SourceParams,
    SourceSnapshot,
    TaskInfo,
    TaskInput,
    TaskParams,
    TaskSnapshot,
)
from .receipt import Receipt

__all__ = [
    # Enums
    "DeliveryMethod",
    "Environment",
    "ResponseStatus",
    "Role",
    "SourceStatus",
    "TaskStatus",
    "combine_environments",
    "environment_names",
    "parse_environments",
    # Errors — base + domain groups
    "OGPUError",
    "NotFoundError",
    "StateError",
    "PermissionError",
    "VaultError",
    "TxError",
    "ConfigError",
    "IPFSError",
    # Errors — concrete classes
    "TaskNotFoundError",
    "SourceNotFoundError",
    "ResponseNotFoundError",
    "ProviderNotFoundError",
    "MasterNotFoundError",
    "TaskExpiredError",
    "TaskAlreadyFinalizedError",
    "ResponseAlreadyConfirmedError",
    "SourceInactiveError",
    "NotTaskOwnerError",
    "NotSourceOwnerError",
    "NotMasterError",
    "NotProviderError",
    "InsufficientBalanceError",
    "InsufficientLockupError",
    "UnbondingPeriodNotElapsedError",
    "NotEligibleError",
    "TxRevertError",
    "NonceError",
    "GasError",
    "InvalidRpcUrlError",
    "MissingSignerError",
    "InvalidSignerError",
    "ChainNotSupportedError",
    "IPFSFetchError",
    "IPFSGatewayError",
    # Receipt
    "Receipt",
    # Metadata
    "SourceMetadata",
    "ImageEnvironments",
    "SourceParams",
    "TaskParams",
    "ResponseParams",
    "SourceInfo",
    "TaskInfo",
    "TaskInput",
    # Snapshots
    "SourceSnapshot",
    "TaskSnapshot",
    "ResponseSnapshot",
]
